CREATE TABLE mvp_data (
    season VARCHAR(10),
    lg VARCHAR(10),
    player VARCHAR(100),
    voting VARCHAR,
    age INT,
    team VARCHAR(50),
    games_played INT,
    minutes_per_game FLOAT,
    points_per_game FLOAT,
    rebounds_per_game FLOAT,
    assists_per_game FLOAT,
    steals_per_game FLOAT,
    blocks_per_game FLOAT,
    fg_percentage FLOAT,
    three_point_percentage FLOAT,
    free_throw_percentage FLOAT,
    wins_shares FLOAT,
    win_shares_per_48 FLOAT
); 
